# Generated by Django 6.0.1 on 2026-02-02 13:18

import django.db.models.deletion
import layers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='projects/previews/', verbose_name='Превью')),
                ('center_lat', models.FloatField(default=64.0, verbose_name='Центр (широта)')),
                ('center_lon', models.FloatField(default=69.0, verbose_name='Центр (долгота)')),
                ('default_zoom', models.IntegerField(default=6, verbose_name='Зум по умолчанию')),
                ('default_basemap', models.CharField(choices=[('osm', 'OpenStreetMap'), ('topo', 'OpenTopoMap'), ('satellite', 'Esri Satellite'), ('dark', 'CartoDB Dark')], default='osm', max_length=20, verbose_name='Базовая карта')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Картографический проект',
                'verbose_name_plural': 'Картографические проекты',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('layer_type', models.CharField(choices=[('vector', 'Векторный'), ('raster', 'Растровый')], default='vector', max_length=10, verbose_name='Тип слоя')),
                ('geom_type', models.CharField(blank=True, choices=[('point', 'Точки'), ('line', 'Линии'), ('polygon', 'Полигоны'), ('multi', 'Смешанный')], default='line', max_length=10, verbose_name='Тип геометрии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('attribution', models.CharField(blank=True, max_length=500, verbose_name='Источник данных')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=layers.models.preview_upload_path, verbose_name='Превью')),
                ('geoserver_layer_name', models.CharField(blank=True, help_text='workspace:layer_name, e.g. geoportal:Морены', max_length=200, verbose_name='Имя слоя в GeoServer')),
                ('postgis_table', models.CharField(blank=True, help_text='Имя таблицы в БД', max_length=200, verbose_name='Таблица в PostGIS')),
                ('source_file', models.FileField(blank=True, help_text='Shapefile (.zip), GeoJSON, GeoTIFF', null=True, upload_to=layers.models.layer_upload_path, verbose_name='Исходный файл')),
                ('raster_file', models.FileField(blank=True, help_text='GeoTIFF для растровых слоёв', null=True, upload_to=layers.models.raster_upload_path, verbose_name='Растровый файл')),
                ('default_visible', models.BooleanField(default=True, verbose_name='Включён по умолчанию')),
                ('opacity', models.FloatField(default=1.0, verbose_name='Прозрачность')),
                ('min_zoom', models.IntegerField(default=0, verbose_name='Мин. зум')),
                ('max_zoom', models.IntegerField(default=18, verbose_name='Макс. зум')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('sld_style', models.TextField(blank=True, help_text='XML-содержимое SLD стиля', verbose_name='SLD стиль')),
                ('stroke_color', models.CharField(default='#3388ff', max_length=7, verbose_name='Цвет линии')),
                ('stroke_width', models.FloatField(default=2.0, verbose_name='Толщина линии')),
                ('fill_color', models.CharField(default='#3388ff', max_length=7, verbose_name='Цвет заливки')),
                ('fill_opacity', models.FloatField(default=0.3, verbose_name='Прозрачность заливки')),
                ('feature_count', models.IntegerField(default=0, verbose_name='Количество объектов')),
                ('bbox_west', models.FloatField(blank=True, null=True, verbose_name='Bbox West')),
                ('bbox_south', models.FloatField(blank=True, null=True, verbose_name='Bbox South')),
                ('bbox_east', models.FloatField(blank=True, null=True, verbose_name='Bbox East')),
                ('bbox_north', models.FloatField(blank=True, null=True, verbose_name='Bbox North')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('projects', models.ManyToManyField(blank=True, related_name='layers', to='layers.mapproject', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Слой',
                'verbose_name_plural': 'Слои',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Имя поля')),
                ('display_name', models.CharField(max_length=200, verbose_name='Отображаемое имя')),
                ('show_in_popup', models.BooleanField(default=True, verbose_name='Показывать в попапе')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='layers.layer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Атрибут слоя',
                'verbose_name_plural': 'Атрибуты слоёв',
                'ordering': ['sort_order'],
                'unique_together': {('layer', 'field_name')},
            },
        ),
    ]
