# Generated by Django 6.0.1 on 2026-02-03 03:50

import django.db.models.deletion
import layers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.IntegerField(help_text='gid объекта из таблицы PostGIS', verbose_name='ID объекта (gid)')),
                ('title', models.CharField(blank=True, help_text='Если пусто — используется название из атрибутов', max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, help_text='Поддерживает HTML-форматирование', verbose_name='Описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=layers.models.feature_image_path, verbose_name='Главное изображение')),
                ('image_caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись к изображению')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='JSON с дополнительными полями', verbose_name='Дополнительные данные')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_contents', to='layers.layer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Контент объекта',
                'verbose_name_plural': 'Контент объектов',
                'ordering': ['layer', 'feature_id'],
                'unique_together': {('layer', 'feature_id')},
            },
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=layers.models.feature_image_path, verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Подпись')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('feature_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='layers.featurecontent', verbose_name='Контент объекта')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Изображения галереи',
                'ordering': ['sort_order'],
            },
        ),
    ]
