# Generated by Django 6.0.1 on 2026-02-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_featurecontent_featureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontent',
            name='image_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка (Яндекс.Диск, Google Drive и др.). Используется если файл не загружен.', max_length=500, verbose_name='Ссылка на изображение'),
        ),
    ]
