# Generated by Django 6.0.1 on 2026-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_featurecontent_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecontent',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, help_text='ID публичной папки с фото для галереи. Пример: 1aBcDeFgHiJkLmNoPqRsTuVwXyZ', max_length=100, verbose_name='ID папки Google Drive'),
        ),
    ]
