# Generated by Django 6.0.1 on 2026-02-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_featurecontent_gdrive_folder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_field', models.CharField(help_text='Имя поля из атрибутов (например: mis, age_type)', max_length=100, verbose_name='Поле для классификации')),
                ('attribute_value', models.CharField(help_text='Значение поля для этого стиля', max_length=200, verbose_name='Значение')),
                ('fill_color', models.CharField(default='#3388ff', max_length=7, verbose_name='Цвет заливки')),
                ('stroke_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет обводки')),
                ('stroke_width', models.FloatField(default=2.0, verbose_name='Толщина обводки')),
                ('fill_opacity', models.FloatField(default=0.8, verbose_name='Прозрачность заливки')),
                ('radius', models.IntegerField(default=8, verbose_name='Радиус (для точек)')),
                ('legend_label', models.CharField(blank=True, help_text='Если пусто — используется значение атрибута', max_length=200, verbose_name='Подпись в легенде')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок в легенде')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='layers.layer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Стиль слоя',
                'verbose_name_plural': 'Стили слоёв',
                'ordering': ['layer', 'sort_order'],
                'unique_together': {('layer', 'attribute_field', 'attribute_value')},
            },
        ),
    ]
