# Generated by Django 6.0.1 on 2026-02-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-адрес')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/covers/', verbose_name='Обложка')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Контент')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.CharField(blank=True, choices=[('glacial', 'Ледниковый рельеф'), ('fluvial', 'Флювиальный рельеф'), ('aeolian', 'Эоловый рельеф'), ('cryogenic', 'Криогенный рельеф')], max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Геоистория',
                'verbose_name_plural': 'Геоистории',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('heading', 'Заголовок'), ('paragraph', 'Текст'), ('image', 'Изображение'), ('gallery', 'Галерея'), ('map', 'Карта'), ('quote', 'Цитата'), ('divider', 'Разделитель'), ('sidecar', 'Сайдкар (карта + текст)')], max_length=50, verbose_name='Тип блока')),
                ('content', models.JSONField(default=dict, verbose_name='Содержимое')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='stories.story')),
            ],
            options={
                'verbose_name': 'Блок истории',
                'verbose_name_plural': 'Блоки историй',
                'ordering': ['sort_order'],
            },
        ),
    ]
