# Generated by Django 6.0.1 on 2026-02-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyblock',
            name='story',
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-адрес')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/covers/', verbose_name='Обложка')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Контент')),
                ('page_type', models.CharField(choices=[('home', 'Главная страница'), ('page', 'Обычная страница'), ('story', 'Геоистория'), ('category', 'Раздел рельефа')], default='page', max_length=20, verbose_name='Тип страницы')),
                ('relief_category', models.CharField(blank=True, choices=[('', '---'), ('glacial', 'Ледниковый рельеф'), ('fluvial', 'Флювиальный рельеф'), ('aeolian', 'Эоловый рельеф'), ('cryogenic', 'Криогенный рельеф')], max_length=50, verbose_name='Категория рельефа')),
                ('menu_position', models.CharField(blank=True, choices=[('', 'Не в меню'), ('main', 'Главное меню'), ('relief', 'Подменю "Рельеф"'), ('footer', 'Футер')], max_length=20, verbose_name='Позиция в меню')),
                ('menu_order', models.IntegerField(default=0, verbose_name='Порядок в меню')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('meta_description', models.TextField(blank=True, verbose_name='META описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='stories.page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='StoryBlock',
        ),
    ]
