# Generated by Django 6.0.1 on 2026-02-04 16:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('content', wagtail.fields.StreamField([('text', 0), ('image', 1), ('map', 5), ('gallery', 8), ('embed', 9), ('cards_grid', 18)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'default': '/geoportal/', 'label': 'URL карты'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '500px', 'label': 'Высота'}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('map_url', 3), ('height', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Изображения'}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('images', 7)]], {}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Видео/Embed'}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 12: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 11), ('text', 12), ('image', 13), ('link', 14), ('external_link', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {'label': 'Карточки'}), 18: ('wagtail.blocks.StructBlock', [[('title', 10), ('cards', 17)]], {})}, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.fields.StreamField([('hero', 3), ('text', 4), ('map', 8), ('cards_grid', 16), ('gallery', 19), ('embed', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 1: ('wagtail.blocks.TextBlock', (), {'label': 'Подзаголовок', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Фоновое изображение', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('background_image', 2)]], {}), 4: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'default': '/geoportal/', 'label': 'URL карты'}), 7: ('wagtail.blocks.CharBlock', (), {'default': '500px', 'label': 'Высота'}), 8: ('wagtail.blocks.StructBlock', [[('title', 5), ('map_url', 6), ('height', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок секции', 'required': False}), 10: ('wagtail.blocks.TextBlock', (), {'label': 'Описание', 'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': False}), 12: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Ссылка на страницу', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'label': 'Внешняя ссылка', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 10), ('image', 11), ('link', 12), ('external_link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'label': 'Карточки'}), 16: ('wagtail.blocks.StructBlock', [[('title', 9), ('cards', 15)]], {}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 18: ('wagtail.blocks.ListBlock', (17,), {'label': 'Изображения'}), 19: ('wagtail.blocks.StructBlock', [[('title', 5), ('images', 18)]], {}), 20: ('wagtail.embeds.blocks.EmbedBlock', (), {'label': 'Видео/Embed'})}, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PublicationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Введение')),
            ],
            options={
                'verbose_name': 'Список публикаций',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GeoStoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('content', wagtail.fields.StreamField([('text', 0), ('image', 1), ('map', 5), ('gallery', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'default': '/geoportal/', 'label': 'URL карты'}), 4: ('wagtail.blocks.CharBlock', (), {'default': '500px', 'label': 'Высота'}), 5: ('wagtail.blocks.StructBlock', [[('title', 2), ('map_url', 3), ('height', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.ListBlock', (6,), {'label': 'Изображения'}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('images', 7)]], {})}, verbose_name='Контент')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'Геоистория',
                'verbose_name_plural': 'Геоистории',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('authors', models.CharField(max_length=500, verbose_name='Авторы')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('journal', models.CharField(blank=True, max_length=300, verbose_name='Журнал/Издание')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Том')),
                ('pages', models.CharField(blank=True, max_length=50, verbose_name='Страницы')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='PDF файл')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-year', 'authors'],
            },
        ),
    ]
